version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/models
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - MODEL_PATH=/models/biomistral-7b-q4.gguf
      - EMBEDDINGS_MODEL=pritamdeka/PubMedBERT-mnli-sts
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  qdrant_data:
